# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Build

on:
  workflow_dispatch:


permissions:
  contents: write

jobs:
  linux-appimage:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7
      with:
        compiler: ldc-latest
  
    - name: "Prepare for AppImage packing"
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse
        sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool.AppImage
        sudo chmod +x /usr/local/bin/appimagetool.AppImage
    
    - name: "Get build dependencies"
      run: |
        sudo apt install libsdl2-dev libfreetype6-dev gettext

    - name: 'Build'
      run: |
        # Build the project, with its main file included, without unittests
        dub build --compiler=ldc2

    - name: 'Build AppImage'
      run: |
        # Build the AppImage
        sudo chmod +x BuildAppImage.sh
        ./BuildAppImage.sh
          
    - name: Archive Zip
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'zyeware-sandbox-linux-x86_64.zip'
        directory: 'out/'
        path: '*'

    - name: Release to nightly tag
      uses: softprops/action-gh-release@v1
      with:
        name: 'Nightly Build'
        tag_name: nightly
        files: |
          build/zyeware-sandbox-x86_64.AppImage
          out/zyeware-sandbox-linux-x86_64.zip
        generate_release_notes: true

  windows-zip:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7
      with:
        compiler: ldc-latest

    - name: 'Build'
      run: |
        function Invoke-VSDevEnvironment {
        $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
              $installationPath = & $vswhere -prerelease -legacy -latest -property installationPath
              $Command = Join-Path $installationPath "Common7\Tools\vsdevcmd.bat"
            & "${env:COMSPEC}" /s /c "`"$Command`" -no_logo && set" | Foreach-Object {
                  if ($_ -match '^([^=]+)=(.*)') {
                      [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
                  }
              }
          }
          Invoke-VSDevEnvironment
          Remove-Item 'C:/Strawberry' -Recurse
          dub build --compiler=ldc2

    - name: Archive Zip
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'zyeware-sandbox-win32-x86_64.zip'
        directory: 'out/'
        path: '*'

    - name: Release to nightly tag
      uses: softprops/action-gh-release@v1
      with:
        name: 'Nightly Build'
        tag_name: nightly
        files: 'out/zyeware-sandbox-win32-x86_64.zip'

  macOS-dmg:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - uses: LunaTheFoxgirl/setup-dlang@v1
      with:
        compiler: ldc-latest
  
    - name: "Prepare for DMG packing"
      run: |
        brew update
        brew install create-dmg gettext

        # Remove conflicting brew items
        brew remove --ignore-dependencies aom cairo composer curl fontconfig freetype gd ghostscript httpd imagemagick jpeg-xl libavif libheif libxft mongodb-community@5.0 mongosh node@16 openjpeg php r sox webp libpng brotli

        # Delete fake harfbuzz if need be
        if [ -f "/usr/local/lib/libharfbuzz.dylib" ]; then
          sudo rm -r /usr/local/lib/libharfbuzz.dylib
        fi

        # And the .a for it as well
        if [ -f "/usr/local/lib/libharfbuzz.a" ]; then
          sudo rm -r /usr/local/lib/libharfbuzz.a
        fi

    - name: 'Build'
      env:
        DFLAGS: "-g -preserve-dwarf-line-section=false"
      run: |

        # First build ARM64 version...
        echo "Building arm64 binary..."
        dub build --config=osx-full --arch=arm64-apple-macos
        mv "out/Zyeware Sandbox.app/Contents/MacOS/zyeware-sandbox" "out/Zyeware Sandbox.app/Contents/MacOS/zyeware-sandbox-arm64"

        # Then the X86_64 version...
        echo "Building x86_64 binary..."
        dub build --config=osx-full --arch=x86_64-apple-macos
        mv "out/Zyeware Sandbox.app/Contents/MacOS/zyeware-sandbox" "out/Zyeware Sandbox.app/Contents/MacOS/zyeware-sandbox-x86_64"

        # Glue them together with lipo
        echo "Gluing them together..."
        lipo "out/Zyeware Sandbox.app/Contents/MacOS/zyeware-sandbox-x86_64" "out/Zyeware Sandbox.app/Contents/MacOS/zyeware-sandbox-arm64" -output "out/Zyeware Sandbox.app/Contents/MacOS/zyeware-sandbox" -create

        # Print some nice info
        echo "Done!"
        lipo -info "out/Zyeware Sandbox.app/Contents/MacOS/zyeware-sandbox"

        # Cleanup and bundle
        echo "Cleaning up..."
        rm "out/Zyeware Sandbox.app/Contents/MacOS/zyeware-sandbox-x86_64" "out/Zyeware Sandbox.app/Contents/MacOS/zyeware-sandbox-arm64"
        ./osxbundle.sh

    - name: 'Build DMG'
      run: |
        ./gendmg.sh

    - name: Release to nightly tag
      uses: softprops/action-gh-release@v1
      with:
        name: 'Nightly Build'
        tag_name: nightly
        files: 'out/Install_Zyeware_Sandbox.dmg'